### PR TITLE
use pagination and load relationships during reindex process

### LINKED ISSUE #37: Reindex in groups instead of all
I experienced exceptions during reindexing (v 1.0.2) with high number of instances, especially when these contained clob / lob / blob. 
Re-Indexing works comparably fast, if performed in bunches of, say, 1000 objects. This can easily be achieved by adding a Pageable as parameter.

Change in method `reindexForClass` :

```java
...
 if (jpaRepository.count() > 0) {
            log.info(entityClass + ":  " + jpaRepository.count());
            int size = 100;
            for (int i = 0; i <= jpaRepository.count() / size; i++) {
                Pageable page = new PageRequest(i, size);
                log.info("Indexing page : " + i + " , nr " + size);
                try {
                    Method m = jpaRepository.getClass().getMethod("findAllWithEagerRelationships", Pageable.class);
                    List<T> paged = (List<T>) m.invoke(jpaRepository, page);
                    elasticsearchRepository.save(paged);
                }

                catch (NoSuchMethodException ex) {
                    log.info(ex.getLocalizedMessage());
                    elasticsearchRepository.save(jpaRepository.findAll(page));
                } catch (Exception ex) {
                    log.error(ex.getMessage());
                    ex.printStackTrace(System.out);
                }
            }
        }
...
```

### PR DESCRIPTION
**Pull request by ruddell**
Should hopefully fix #37 and #17.  It uses `findAll(pageable)` for all entities, then loads any relationships eagerly.  If it's not what you are looking for, feel free to close.

I couldn't get any OutOfMemoryErrors, any special instructions to reproduce would help.  I tested with a dockerized app, limiting memory via JAVA_OPTS.  I had a couple hundred entities of each type using the following JDL:
```
// JDL definition for application 'elastic' generated with command 'jhipster export-jdl'

entity Foo (foo) {
  name String
}
entity Bar (bar) {
  name String
}
entity Baz (baz) {
  name String
}
entity DoubleRelationship (tree_top) {
  name String
}

relationship ManyToMany {
  Bar{foo(name)} to Foo{bar},
  Baz{bar(name)} to Bar{baz},
  DoubleRelationship{baz(name)} to Baz{DoubleRelationship},
  DoubleRelationship{bar(name)} to Bar{DoubleRelationship}
}

dto Foo, Bar, Baz, DoubleRelationship with mapstruct
paginate Foo, Bar, Baz, DoubleRelationship with pagination
service Foo, Bar, Baz, DoubleRelationship with serviceClass
```

### CODE REVIEW

File: generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java [hunk 1]
```diff
@@ -141,11 +147,30 @@ public void reindexAll() {
...
+            for (int i = 0; i <= jpaRepository.count() / size; i++) {
+                Pageable page = new PageRequest(i, size);
+                log.info("Indexing page : " + i + " , nr " + size);
+                Page<T> results = jpaRepository.findAll(page);
+                results.map(result -> {
+                    // if there are any relationships to load, do it now
+                    relationshipGetters.forEach(method -> {
+                        try {
+                            // eagerly load the relationship set
+                            ((Set) method.invoke(result)).size();
```
Comment (ruddell) [inline generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: [An example of what this would normally look like](https://github.com/jhipster/generator-jhipster/blob/v2.x_maintenance/app/templates/src/main/java/package/service/_UserService.java#L185-L187)

**Comment by geraldhumphries** [comment]
This will load all relationships containing a set, which includes one-to-many relationships as well as non-owner many-to-many relationships. The only relationships that need to be loaded manually are owner-side many-to-many relationships, the ones covered by `findAllWithEagerRelationships()`.

For default generated entities this would probably work properly because the non-owner sides of these relationships are annotated with `@JsonIgnore`. However it's not ideal because these relationships will be loaded unnecessarily.

I would suggest we change the method to only get the necessary relationships by matching the parameters used to generate `findAllWithEagerRelationships()` methods. See here: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/repository/_EntityRepository.java#L79

Change relationshipGetters to this: ```
            List<Method> relationshipGetters = Arrays.stream(entityClass.getDeclaredFields())
                .filter(field -> field.getType().equals(Set.class))
                .filter(field -> field.getAnnotation(ManyToMany.class) != null)
                .filter(field -> field.getAnnotation(ManyToMany.class).mappedBy().isEmpty())
                .filter(field -> field.getAnnotation(JsonIgnore.class) == null)
                .map(field -> {
                    try {
                        return new PropertyDescriptor(field.getName(), entityClass).getReadMethod();
                    } catch (IntrospectionException e) {
                        log.error("Error retrieving getter for class {}, field {}", entityClass.getSimpleName(), field.getName(), e);
                        return null;
                    }
                })
                .filter(Objects::nonNull)
                .collect(Collectors.toList());
```

File: generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java [hunk 2]
```diff
@@ -141,11 +147,30 @@ public void reindexAll() {
...
+                        } catch (Exception ex) {
+                            log.error(ex.getMessage());
+                        }
+                    });
+                    return result;
+                });
+                elasticsearchRepository.save(results);
```
Comment (geraldhumphries) [inline generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: This needs to be `elasticsearchRepository.save(results.getContent())`. The save method will throw an exception if it doesn't receive the collection itself.

File: generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java [hunk 3]
```diff
@@ -141,11 +147,30 @@ public void reindexAll() {
...
+            // set up a list of relationships that should be eagerly loaded.
+            // if a JHipster entity field is a Set, it is a relationship
+            List<Method> relationshipGetters = Arrays.stream(entityClass.getDeclaredMethods())
+                .filter(method -> method.getReturnType().equals(Set.class))
+                .collect(Collectors.toList());
+
+            int size = 100;
+            for (int i = 0; i <= jpaRepository.count() / size; i++) {
+                Pageable page = new PageRequest(i, size);
+                log.info("Indexing page : " + i + " , nr " + size);
```
Comment (geraldhumphries) [inline generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: Can you change this to `log.info("Indexing page {} of {}, size {}", i, jpaRepository.count() / size, size);`?

File: generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java [hunk 4]
```diff
@@ -141,11 +147,30 @@ public void reindexAll() {
         }
         elasticsearchTemplate.putMapping(entityClass);
         if (jpaRepository.count() > 0) {
-            try {
-                Method m = jpaRepository.getClass().getMethod("findAllWithEagerRelationships");
-                elasticsearchRepository.save((List<T>) m.invoke(jpaRepository));
-            } catch (Exception e) {
-                elasticsearchRepository.save(jpaRepository.findAll());
+            // set up a list of relationships that should be eagerly loaded.
+            // if a JHipster entity field is a Set, it is a relationship
```
Comment (geraldhumphries) [inline generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: Update this comment to `// if a JHipster entity field is the owner side of a many-to-many relationship, it should be loaded manually`

File: generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java [hunk 5]
```diff
@@ -129,7 +136,6 @@ public void reindexAll() {
         }
     }
 
-    @Transactional(readOnly = true)
```
[the remark this answers is not in the document]
Comment (ruddell) [reply generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: Without moving the `@Transactional`, I get `ERROR ElasticsearchIndexService  : failed to lazily initialize a collection of role: com.mycompany.myapp.domain.Foo.bars, could not initialize proxy - no Session`. Do you have a sample entity config that causes issues? Also what does your IDE want the method to be?

[the remark this answers is not in the document]
Comment (geraldhumphries) [reply generators/app/templates/src/main/java/package/service/_ElasticsearchIndexService.java]: My IDE wanted the method to be public or protected if I used a method-level transaction.

I get the same error. It's probably what @FireWolf2007 mentioned in https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer/issues/17#issuecomment-345619190

This is probably okay to merge now. I will do some more testing to make sure #10 does not regress.
